// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvguQjlMgHJpfStG7vSE2yqbAaWvrGe3g',
    appId: '1:465556819993:web:8205a9ab996548f64b1a88',
    messagingSenderId: '465556819993',
    projectId: 'social-app-96df9',
    authDomain: 'social-app-96df9.firebaseapp.com',
    storageBucket: 'social-app-96df9.appspot.com',
    measurementId: 'G-0WFLHT0ZGZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmD6CGie7XsWcGCdu6YeznYw7XaltkNjs',
    appId: '1:465556819993:android:1c97a6de50155fbe4b1a88',
    messagingSenderId: '465556819993',
    projectId: 'social-app-96df9',
    storageBucket: 'social-app-96df9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDry-QqBjaSbRjbMF_YFPs8INVTSAODAos',
    appId: '1:465556819993:ios:39133811d36bdc644b1a88',
    messagingSenderId: '465556819993',
    projectId: 'social-app-96df9',
    storageBucket: 'social-app-96df9.appspot.com',
    androidClientId: '465556819993-fo7dga649umpqc7vpi2iq6bkbl5kfgle.apps.googleusercontent.com',
    iosClientId: '465556819993-it8giteg68spjb2qatvv2fl2fhfj5bma.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDry-QqBjaSbRjbMF_YFPs8INVTSAODAos',
    appId: '1:465556819993:ios:6c63811db5febaa54b1a88',
    messagingSenderId: '465556819993',
    projectId: 'social-app-96df9',
    storageBucket: 'social-app-96df9.appspot.com',
    androidClientId: '465556819993-fo7dga649umpqc7vpi2iq6bkbl5kfgle.apps.googleusercontent.com',
    iosClientId: '465556819993-osda9u0duqdgptqs2sc7sens7bm3r1u9.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
